<?php $product = $this->getProduct() ?>
<form method="POST" action="<?= $block->getUrl('mcp/import/save') ?>">
sku<input type="text" name="sku" value="<?= $product->Sku ?>">
name<input type="text" name="productname" value="<?= $product->ProductName ?>">
Description<input type="text" name="desc">
<input type="hidden" name="form_key" value="<?= $this->getFormKey() ?>" />
<input type="submit">
</form>