<h1> This is all the stuff you can sell </h1>
<table border='1' >
<tr><th>SKU</th><th>Name</th></tr>
<?php
$stuff = $this->getStuff();
foreach ($stuff as $value) {
    $currentUrl = Mage::helper('core/url')->getCurrentUrl();
    $url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
    $path = $url->getPath();
    ?><tr><td><a href="<?= $path.'?'.$value->Sku ?>"></a></td><td><?= $value->ProductName ?></td></tr><?php
}
?></table>